apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: toscanini
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  TOSCANINI_DATA_DIR: {{ .Values.global.dataDir | quote }}
  REDIS_URL:          {{ .Values.global.redisUrl | quote }}
  BRAIN_URL:          "http://{{ .Release.Name }}-brain:{{ .Values.brain.port }}"
  BACKEND_URL:        "http://{{ .Release.Name }}-brain:{{ .Values.brain.port }}"
