apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-face
  labels:
    app.kubernetes.io/name: toscanini-face
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.face.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-face
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-face
    spec:
      containers:
        - name: face
          image: "{{ .Values.face.image.repository }}:{{ .Values.face.image.tag }}"
          imagePullPolicy: {{ .Values.face.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.face.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          resources:
            {{- toYaml .Values.face.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-face
  labels:
    app.kubernetes.io/name: toscanini-face
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-face
  ports:
    - port: {{ .Values.face.port }}
      targetPort: {{ .Values.face.port }}
