apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: toscanini
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  TOSCANINI_API_KEY: {{ .Values.brain.secrets.TOSCANINI_API_KEY | quote }}
  GEMINI_API_KEY:    {{ .Values.brain.secrets.GEMINI_API_KEY | quote }}
